[package]
name = "git-hired"
version = "0.1.2"
entrypoint = "src/lib.typ"
authors = ["Orest Tokovenko <www.oresttokovenko.com>"]
license = "MIT"
description = "A modern, minimal resume template for tech professionals"
compiler = "0.14.0"
repository = "https://github.com/oresttokovenko/git-hired"
exclude = [
	".github",
	"tests",
	".typstignore",
	"justfile",
]
